[agent.host]
# it is under the Path.home() use relative path
data_dir = "kubent/data"
[agent.host.kubent]
# the first kubent is project name and the second kubent is the agent name
# relative path: home()/kubent/data/kubent/conversations
conversations_dir = "kubent/conversations"

[agent.docker]
work_dir = "/workspace"
conversations_dir = "/workspace/conversations"

[robin]
model = "anthropic/claude-haiku-4.5"

[robin.parse]
model = "qwen2.5-72b-instruct"

[robin.think]
model = "x-ai/grok-4.1-fast"

[kubent]
model = "anthropic/claude-haiku-4.5"

[kubent.think]
model = "x-ai/grok-4.1-fast"

[query_step]
model = "qwen/qwen3-4b:free"

[service.chat]
model = "openai/gpt-oss-20b"

[utils.solve_context_length]
model = "openai/gpt-oss-20b"
context_length = 65536
